.TH mlmmj-unsub "1" "September 2004" mlmmj-unsub
.SH NAME
mlmmj-unsub \- manual page for mlmmj-unsub
.SH SYNOPSIS
.B mlmmj-unsub
\fI-L /path/to/list -a john@doe.org\fR [\fI-b\fR] [\fI-c\fR | \fI-C\fR]
[\fI-d\fR | \fI-n\fR] [\fI-h\fR] [\fI-r\fR | \fI-R\fR] [\fI-s\fR] [\fI-U\fR] [\fI-V\fR]
.HP
\fB\-a\fR: Email address to unsubscribe
.HP
\fB\-b\fR: Behave as if unsubscription is due to bouncing (internal use)
.HP
\fB\-c\fR: Send goodbye mail
.HP
\fB\-C\fR: Request mail confirmation
.HP
\fB\-d\fR: Unsubscribe from the digest version of the list
.HP
\fB\-h\fR: This help
.HP
\fB\-L\fR: Full path to list directory
.HP
\fB\-n\fR: Unsubscribe from the nomail version of the list
.HP
\fB\-r\fR: Behave as if request arrived via email (internal use)
.HP
\fB\-R\fR: Behave as if confirmation arrived via email (internal use)
.HP
\fB\-s\fR: Don't send a mail to the address if not subscribed
.HP
\fB\-U\fR: Don't switch to the user id of the listdir owner
.HP
\fB\-V\fR: Print version
.SH DESCRIPTION
This utility is used to unsubscribe people from the specified mailinglist. It
will remove the specified email address from every file in the
<listdir>/subscribers.d/ directory.

Unless the \fB\-U\fR switch is used it will switch its user id to the user id
owning the list directory. This is done to make sure that new files created are
having correct permissions.

Normally a mail is sent to the person being unsubscribed if the address is not
subscribed to the list. If the \fB\-s\fR switch is used such a mail will not be
sent.

When neither \fB\-c\fR nor \fB\-C\fR are specified, unsubscription silently
happens.
.SH "SEE ALSO"
mlmmj-sub(1)
.SH AUTHORS
This manual page was written by the following persons:
.HP
Søren Boll Overgaard <boll@debian.org> (based on html2man output)
.HP
Mads Martin Jørgensen <mmj@mmj.dk>
