.TH mlmmj-list "1" "November 2004" mlmmj-receive
.SH NAME
mlmmj-list \- list people / subscribers associated with a list
.SH SYNOPSIS
.B mlmmj-list
\fI\-L /path/to/listdir \fR[\fI\-c\fR] \fR[\fI\-d\fR] \fR[\fI\-h\fR] [\fI\-m\fR] [\fI\-n\fR] [\fI\-o\fR] \fR[\fI\-s\fR] \fR[\fI\-V\fR]
.HP
\fB\-c\fR: Count the emailaddresses
.HP
\fB\-d\fR: Print for digesters list
.HP
\fB\-L\fR: Full path to list directory
.HP
\fB\-m\fR: Print moderators for list
.HP
\fB\-n\fR: Print for nomail version of list
.HP
\fB\-o\fR: Print the owner(s) of the list
.HP
\fB\-s\fR: Print normail subscribers (default)
.HP
\fB\-V\fR: Print version

.SH AUTHORS
This manual page was written by the following person:
.HP
Mads Martin Jørgensen <mmj@mmj.dk>
