.TH mlmmj-make-ml "1" "September 2004" mlmmj-make-ml
.SH NAME
mlmmj-make-ml \- create a mailing list for mlmmj
.SH SYNOPSIS
.B mlmmj-make-ml
\fI[OPTIONS]
.HP
\fB\-h\fR: Display help
.HP
\fB\-L\fR: The name of the mailing list
.HP
\fB\-s\fR: The spool directory, if different from /var/spool/mlmmj
.HP
\fB\-a\fR: Create the needed entries in /etc/aliases
.HP
\fB\-z\fR: Do nothing for now.
.SH DESCRIPTION
This is an interactive script which creates the mailing list directory and thus
the list itself for being run by mlmmj.
.SH BUGS
It's not possible to create a mailinglist entirely on the command line.
.SH AUTHORS
This manual page was written by the following persons:
.HP
Søren Boll Overgaard <boll@debian.org> (based on html2man output)
.HP
Mads Martin Jørgensen <mmj@mmj.dk>
